package com.lillytech.aischool.core.model

/**
 * Structured mirror of the AI School catalog, generated from the content
 * pipeline's feed by `pipeline/bundle_into_apps.py`.
 *
 * The network layer prefers the live `syllabus.json` feed; this seed keeps
 * both app flavors fully functional offline (and is the bundled, no-hosting
 * content of record). Do not hand-edit; re-run the bundler to refresh.
 */
object SeedSyllabus {

    val courses: List<Course> = listOf(
        Course(
            id = "anthropic-claude-claude-models-overview",
            title = "Claude Models Overview",
            description = "Master the Claude model family tiers and the decision chain that turns them into production features.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-claude-models-overview-claude-family-overview",
                    title = "Claude Family Overview",
                    durationSeconds = 238,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/claude-family-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the Claude model family tiers and the decision chain that turns them into production features.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-opus-sonnet-haiku-positioning",
                    title = "Opus / Sonnet / Haiku Positioning",
                    durationSeconds = 279,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/opus-sonnet-haiku-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude's three model tiers—Opus, Sonnet, and Haiku—and build production systems that survive growth and upgrades.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-family-pricing-shape",
                    title = "Family Pricing Shape",
                    durationSeconds = 358,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/family-pricing-shape.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right Claude model tier and build a defensible decision-making chain for shipping production-grade AI features.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-context-windows-across-the-family",
                    title = "Context Windows Across the Family",
                    durationSeconds = 305,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/context-windows-across-the-family.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right Claude model tier—Opus, Sonnet, or Haiku—and design your context strategy for production systems.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-family-vs-external-models",
                    title = "Family vs External Models",
                    durationSeconds = 273,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/family-vs-external-models.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude's model tiers and external models, then operationalize that choice through a disciplined engineering pattern that covers prompts, tools, evaluation, and production deployment.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-picking-a-family-tier",
                    title = "Picking a Family Tier",
                    durationSeconds = 235,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/picking-a-family-tier.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to pick the right Claude model tier—Opus, Sonnet, or Haiku—and build a defensible decision-making chain for shipping Claude-backed features into production.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-opus-deep-dive",
            title = "Opus Deep Dive",
            description = "Master Claude Opus 4.7 by treating AI development as a deliberate chain of engineering decisions: model selection, prompt design, tool integration, context strategy, evaluation, and production scaffolding.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-47-overview",
                    title = "Opus 4.7 Overview",
                    durationSeconds = 252,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-47-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Opus 4.7 by treating AI development as a deliberate chain of engineering decisions: model selection, prompt design, tool integration, context strategy, evaluation, and production scaffolding.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-1m-context-capability",
                    title = "1M Context Capability",
                    durationSeconds = 253,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/1m-context-capability.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Opus 4.7's 1-million-token context window by anchoring every build decision in user-facing metrics, picking the right model tier, designing structured prompts, wiring tools carefully, engineering your context strategy, building evaluation sets before shipping, and deploying with operational rigor.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-frontier-reasoning",
                    title = "Frontier Reasoning",
                    durationSeconds = 213,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/frontier-reasoning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the complete engineering framework for building Claude Opus-backed systems in production, from model selection through deployment with evals and operational safety.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-cost-latency-profile",
                    title = "Cost & Latency Profile",
                    durationSeconds = 220,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/cost-latency-profile.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to pick the right Claude model tier and operationalize it inside a production system by reasoning through a chain of interconnected engineering decisions.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-vs-sonnet-decision",
                    title = "Opus vs Sonnet Decision",
                    durationSeconds = 238,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-vs-sonnet-decision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude Opus and Sonnet by anchoring decisions in user-facing metrics, then optimizing for latency, cost, and quality alongside prompt design, tooling, evaluation, and production operations.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-workload-patterns",
                    title = "Opus Workload Patterns",
                    durationSeconds = 302,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to build production Claude features by anchoring decisions in user value, selecting the right model tier, designing prompts and tools methodically, and shipping with evals and operational safeguards.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-sonnet-deep-dive",
            title = "Sonnet Deep Dive",
            description = "Master Claude Sonnet 4.6 as a production-ready model by understanding its role in the price-quality-latency trade-off, learning the decision chain that makes Claude features work at scale, and building operational discipline around evals, monitoring, and incident response.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-sonnet-46-overview",
                    title = "Sonnet 4.6 Overview",
                    durationSeconds = 186,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/sonnet-46-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Sonnet 4.6 as a production-ready model by understanding its role in the price-quality-latency trade-off, learning the decision chain that makes Claude features work at scale, and building operational discipline around evals, monitoring, and incident response.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-production-workhorse-positioning",
                    title = "Production Workhorse Positioning",
                    durationSeconds = 276,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/production-workhorse-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Sonnet as your production AI workhorse by treating it as a deliberate chain of engineering decisions from model selection through operational deployment.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-price-quality-latency-trade-off",
                    title = "Price / Quality / Latency Trade-off",
                    durationSeconds = 334,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/price-quality-latency-trade-off.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to navigate the price, quality, and latency trade-offs when choosing Claude models and building production systems.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-sonnet-workload-patterns",
                    title = "Sonnet Workload Patterns",
                    durationSeconds = 245,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/sonnet-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the practical decision chain for shipping Claude Sonnet features in production, from model selection through deployment with observability and evals.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-migrating-from-earlier-sonnet",
                    title = "Migrating from Earlier Sonnet",
                    durationSeconds = 256,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/migrating-from-earlier-sonnet.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn a seven-step production pattern for migrating to Claude Sonnet and building reliable AI features that scale.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-opus-sonnet-cascade",
                    title = "Opus-Sonnet Cascade",
                    durationSeconds = 331,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/opus-sonnet-cascade.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the Opus-Sonnet cascade pattern: a systematic decision-making framework for building production Claude applications that balance cost, latency, and quality.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-haiku-deep-dive",
            title = "Haiku Deep Dive",
            description = "Master Claude Haiku 4.5 as your default fast-and-cheap model by understanding when to use it, how to design prompts and tools around it, and how to operationalize it in production with evals and monitoring.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-45-overview",
                    title = "Haiku 4.5 Overview",
                    durationSeconds = 196,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-45-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku 4.5 as your default fast-and-cheap model by understanding when to use it, how to design prompts and tools around it, and how to operationalize it in production with evals and monitoring.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-fast-cheap-positioning",
                    title = "Fast & Cheap Positioning",
                    durationSeconds = 247,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/fast-cheap-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku for fast and cheap production work by anchoring decisions in user metrics, choosing the right model tier, and building evaluation loops before shipping.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-workload-patterns",
                    title = "Haiku Workload Patterns",
                    durationSeconds = 212,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku by understanding the decision chain for model selection, prompt design, tool wiring, context strategy, evaluation, and production deployment.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-latency-targets",
                    title = "Latency Targets",
                    durationSeconds = 249,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/latency-targets.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to systematically choose Claude models, design prompts, and operationalize AI features in production by anchoring decisions in user value, latency constraints, and evaluation-driven iteration.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-cost-optimisation",
                    title = "Cost Optimisation",
                    durationSeconds = 235,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/cost-optimisation.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master cost optimization for Claude by treating AI development as a deliberate chain of decisions from model selection through production operations, with evaluation and monitoring at every step.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-first-design-pattern",
                    title = "Haiku-First Design Pattern",
                    durationSeconds = 211,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-first-design-pattern.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the haiku-first design pattern: a systematic seven-step approach to building production Claude applications that balance cost, latency, and quality through deliberate model selection, prompt engineering, tooling, context strategy, evaluation, and operational scaffolding.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-model-selection",
            title = "Model Selection",
            description = "Learn the decision framework and operational discipline for selecting the right Claude model and building production-ready AI features.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-model-selection-model-selection-overview",
                    title = "Model Selection Overview",
                    durationSeconds = 236,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/model-selection-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the decision framework and operational discipline for selecting the right Claude model and building production-ready AI features.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-decision-framework",
                    title = "Decision Framework",
                    durationSeconds = 216,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/decision-framework.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn a practical decision framework for choosing Claude models and building production-ready AI features by reasoning through latency, cost, quality, prompts, tools, evaluation, and operational scaffolding.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-benchmark-mapping",
                    title = "Benchmark Mapping",
                    durationSeconds = 195,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/benchmark-mapping.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the benchmark mapping framework to select the right Claude model for each production use case by anchoring decisions in user-facing metrics, cost and latency budgets, and rigorous evaluation.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-cascade-pattern",
                    title = "Cascade Pattern",
                    durationSeconds = 263,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/cascade-pattern.html",
                    isAutomotiveSafe = true,
                    audioSummary = "The cascade pattern is a decision-making framework for selecting and deploying Claude models in production systems, balancing latency, cost, and quality through deliberate evaluation and operational scaffolding.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-eval-discipline",
                    title = "Eval Discipline",
                    durationSeconds = 279,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/eval-discipline.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Eval discipline is a systematic approach to building and operating Claude-backed features in production by anchoring every decision in measurable outcomes, testing rigorously before shipping, and maintaining observability at scale.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-selection-template",
                    title = "Selection Template",
                    durationSeconds = 232,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/selection-template.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the end-to-end decision framework and operational pattern for building production Claude features that scale, from model selection through deployment with observability and evals.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-claude-code",
            title = "Claude Code",
            description = "Learn how to set up and master Claude Code, a terminal-native AI coding agent, by understanding its core workflows, slash commands, configuration patterns, and when to use it effectively.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-claude-code-claude-code-overview",
                    title = "Claude Code Overview",
                    durationSeconds = 247,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to set up and master Claude Code, a terminal-native AI coding agent, by understanding its core workflows, slash commands, configuration patterns, and when to use it effectively.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-slash-commands",
                    title = "Slash Commands and Skills",
                    durationSeconds = 210,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-slash-commands.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn slash commands and skills in Claude Code CLI to unlock power-user workflows and automation patterns.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-hooks",
                    title = "Hooks and Automation",
                    durationSeconds = 213,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-hooks.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use hooks and automation in Claude Code CLI to trigger actions automatically and build faster, smarter coding workflows.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-subagents",
                    title = "Sub-Agents and Parallelism",
                    durationSeconds = 193,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-subagents.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use sub-agents and parallelism in Claude Code to work faster by understanding when and how to leverage these advanced features effectively.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-mcp",
                    title = "MCP Servers",
                    durationSeconds = 226,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-mcp.html",
                    isAutomotiveSafe = true,
                    audioSummary = "MCP servers let you extend Claude Code with custom integrations and data sources, turning it from a general-purpose tool into a purpose-built agent for your specific workflow.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-team-workflows",
                    title = "Team Workflows and Settings",
                    durationSeconds = 269,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-team-workflows.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to configure Claude Code CLI for your team by understanding the deliberate workflow choices, core settings, and production patterns that separate casual users from power users.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-cursor-editor",
            title = "Cursor Editor",
            description = "Cursor Overview teaches you how to think strategically about the Cursor AI editor and apply it effectively to real workflows, not just memorize its features.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-overview",
                    title = "Cursor Overview",
                    durationSeconds = 236,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Cursor Overview teaches you how to think strategically about the Cursor AI editor and apply it effectively to real workflows, not just memorize its features.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-tab",
                    title = "Cursor Tab Autocomplete",
                    durationSeconds = 192,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-tab.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use Cursor's Tab autocomplete feature effectively by understanding when and why to use it, how to set it up, and the habits that distinguish power users from casual users.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-composer-agent",
                    title = "Composer and Agent Mode",
                    durationSeconds = 206,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-composer-agent.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Composer and Agent Mode in Cursor to write code faster, and understand the mental models that separate power users from casual users.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-rules",
                    title = "cursorrules and Project Rules",
                    durationSeconds = 284,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-rules.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use .cursorrules and project rules in Cursor to configure your AI coding assistant with team standards, keyboard shortcuts, and context protocols for faster, consistent development workflows.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-mcp",
                    title = "Cursor MCP Integration",
                    durationSeconds = 243,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-mcp.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to integrate Model Context Protocol servers into Cursor to extend the editor's capabilities and accelerate your coding workflow.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-team",
                    title = "Cursor for Teams",
                    durationSeconds = 182,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-team.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to set up and use Cursor for Teams effectively by treating it as a deliberate workflow choice with proper configuration, security, and team coordination.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-github-copilot-tool",
            title = "GitHub Copilot Tool",
            description = "GitHub Copilot Overview teaches you how to use AI coding assistants effectively by understanding the tool's strengths, configuring it deliberately, and building it into your workflow rather than treating it as a silver bullet.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-overview",
                    title = "Copilot Overview",
                    durationSeconds = 247,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GitHub Copilot Overview teaches you how to use AI coding assistants effectively by understanding the tool's strengths, configuring it deliberately, and building it into your workflow rather than treating it as a silver bullet.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-inline-chat",
                    title = "Inline Suggestions and Chat",
                    durationSeconds = 227,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-inline-chat.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use GitHub Copilot's inline suggestions and chat features as a deliberate workflow choice, not a default habit.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-workspace",
                    title = "Copilot Workspace",
                    durationSeconds = 255,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-workspace.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Copilot Workspace is a deliberate workflow choice that amplifies your coding speed through configuration, shortcuts, and whole-codebase context.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-agent-mode",
                    title = "Copilot Agent Mode",
                    durationSeconds = 247,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-agent-mode.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Copilot Agent Mode is a deliberate workflow choice that separates casual users from power users through understanding underlying patterns and integrating the tool strategically into your development process.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-instructions",
                    title = "Custom Instructions",
                    durationSeconds = 209,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-instructions.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Custom instructions in GitHub Copilot are deliberate workflow choices that let power users shape how the AI assistant behaves, making the difference between casual and expert-level productivity.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-enterprise",
                    title = "Copilot Enterprise",
                    durationSeconds = 194,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-enterprise.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use GitHub Copilot Enterprise as a deliberate workflow choice by understanding its strengths, configuring it smartly, and building habits that compound your productivity.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-aider",
            title = "Aider",
            description = "Aider is a terminal-based AI pair programmer that edits code with Git awareness, and mastering it means understanding its core workflows and knowing when to actually use it.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-aider-aider-overview",
                    title = "Aider Overview",
                    durationSeconds = 219,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Aider is a terminal-based AI pair programmer that edits code with Git awareness, and mastering it means understanding its core workflows and knowing when to actually use it.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-architect-edit",
                    title = "Architect and Edit Modes",
                    durationSeconds = 178,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-architect-edit.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Architect and edit modes in Aider let you choose between planning-first workflows and direct editing, turning you from casual user to power user through deliberate mode selection.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-repo-map",
                    title = "Repo Map",
                    durationSeconds = 232,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-repo-map.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Repo map in Aider is a deliberate workflow choice that separates casual users from power users—learn when to use it, how it fits into your coding process, and the mental models that make AI pair programming faster.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-git",
                    title = "Git-Aware Editing",
                    durationSeconds = 177,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-git.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Git-aware editing is a deliberate workflow choice that separates casual Aider users from power users through intentional patterns, tool configuration, and habits.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-voice",
                    title = "Aider Voice Coding",
                    durationSeconds = 220,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-voice.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master aider voice coding by treating it as a deliberate workflow choice, understanding the tool's idioms, and building habits that compound your productivity over time.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-models",
                    title = "Choosing Models for Aider",
                    durationSeconds = 187,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-models.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to deliberately choose the right AI model for Aider based on your workflow needs, pricing, and tool strengths rather than defaulting to recommendations.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-continue-dev",
            title = "Continue Dev",
            description = "Continue is an open-source AI coding assistant that integrates into your IDE, and mastering it means understanding its strengths and building deliberate workflows rather than defaulting to how it's marketed.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-continue-dev-continue-overview",
                    title = "Continue Overview",
                    durationSeconds = 200,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Continue is an open-source AI coding assistant that integrates into your IDE, and mastering it means understanding its strengths and building deliberate workflows rather than defaulting to how it's marketed.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-config",
                    title = "config.json Configuration",
                    durationSeconds = 268,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-config.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to configure Continue's config.json file to customize your AI coding assistant with models, context providers, and custom commands.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-context-providers",
                    title = "Context Providers",
                    durationSeconds = 224,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-context-providers.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Context providers in Continue let you give your AI coding assistant the right project information at the right time, turning casual users into power users through deliberate workflow choices.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-custom-commands",
                    title = "Custom Slash Commands",
                    durationSeconds = 158,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-custom-commands.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to create and configure custom slash commands in Continue to extend the AI coding assistant's capabilities and match your unique workflow.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-self-hosted",
                    title = "Self-Hosted Continue",
                    durationSeconds = 241,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-self-hosted.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to self-host Continue, configure it for your workflow, and avoid the common pitfall of adopting tools before you understand what you actually need.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-vs-cursor",
                    title = "Continue vs Cursor",
                    durationSeconds = 202,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-vs-cursor.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to choose between Continue and Cursor as your AI coding assistant, and how to build productive workflows around whichever tool fits your actual needs.",
                ),
            ),
        ),
        Course(
            id = "ai-models-gpt-5",
            title = "GPT-5",
            description = "Learn how to evaluate and choose GPT-5 for your AI project by understanding its real capabilities, tradeoffs, and production patterns rather than relying on marketing hype.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-overview",
                    title = "GPT-5 Overview",
                    durationSeconds = 214,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate and choose GPT-5 for your AI project by understanding its real capabilities, tradeoffs, and production patterns rather than relying on marketing hype.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-capabilities",
                    title = "GPT-5 Capabilities and Benchmarks",
                    durationSeconds = 249,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-capabilities.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate GPT-5's real capabilities and benchmarks to make smart model choices for your AI projects instead of just picking the trendy option.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-context-multimodal",
                    title = "Context Window and Multimodal",
                    durationSeconds = 251,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-context-multimodal.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to strategically choose GPT-5 based on context window and multimodal capabilities rather than defaulting to it, and understand the engineering patterns that let you match models to workloads in production.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-tool-use",
                    title = "Native Tool Use",
                    durationSeconds = 217,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-tool-use.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Native tool use in GPT-5 is a deliberate engineering decision that should match your workload's actual needs, not be chosen by default.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-pricing",
                    title = "Pricing and Cost Optimization",
                    durationSeconds = 201,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-pricing.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right AI model for your task by understanding GPT-5's pricing, capabilities, and real-world trade-offs.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-production",
                    title = "GPT-5 in Production",
                    durationSeconds = 201,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to confidently deploy GPT-5 in production by understanding its capabilities, trade-offs, and the engineering patterns that separate successful implementations from costly mistakes.",
                ),
            ),
        ),
        Course(
            id = "ai-models-gpt-4o",
            title = "GPT-4o",
            description = "GPT-4o is OpenAI's versatile multimodal model that handles text, vision, and audio—learn how to choose it wisely by matching its actual capabilities to your workload rather than defaulting to it.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-overview",
                    title = "GPT-4o Overview",
                    durationSeconds = 219,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GPT-4o is OpenAI's versatile multimodal model that handles text, vision, and audio—learn how to choose it wisely by matching its actual capabilities to your workload rather than defaulting to it.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-vision",
                    title = "GPT-4o Vision",
                    durationSeconds = 230,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-vision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use GPT-4o Vision as a deliberate engineering choice, not a default, by understanding its strengths, costs, and production patterns.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-audio",
                    title = "GPT-4o Audio",
                    durationSeconds = 270,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-audio.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use GPT-4o's audio and realtime capabilities in production systems, and understand the engineering trade-offs that determine whether it's the right model choice.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-mini",
                    title = "GPT-4o-mini for Cost",
                    durationSeconds = 234,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-mini.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to pick GPT-4o-mini strategically for cost without sacrificing quality, and the engineering patterns that let you make confident model choices in production.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-structured-outputs",
                    title = "Structured Outputs",
                    durationSeconds = 180,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-structured-outputs.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Structured outputs is a deliberate engineering choice that lets you get predictable, validated responses from GPT-4o, but only if it actually fits your workload.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-production",
                    title = "GPT-4o in Production",
                    durationSeconds = 273,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to deploy GPT-4o in production systems by understanding its actual capabilities, measuring performance on your data, and making deliberate model choices rather than defaulting to the flagship.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-opus-4-7",
            title = "Claude Opus 4.7",
            description = "Learn how to evaluate and choose Claude Opus 4.7 strategically based on your actual workload requirements rather than hype.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-overview",
                    title = "Claude Opus 4.7 Overview",
                    durationSeconds = 207,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate and choose Claude Opus 4.7 strategically based on your actual workload requirements rather than hype.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-1m-context",
                    title = "1M Token Context Window",
                    durationSeconds = 232,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-1m-context.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Opus 4.7's 1M token context window as a deliberate engineering choice, not a default.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-coding",
                    title = "Opus 4.7 for Coding",
                    durationSeconds = 174,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-coding.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and use Claude Opus 4.7 for coding tasks by understanding its capabilities, pricing, and production patterns.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-agents",
                    title = "Opus 4.7 for Agents",
                    durationSeconds = 222,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-agents.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and deploy Claude Opus 4.7 strategically for agent-based systems, focusing on real-world engineering decisions rather than marketing claims.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-vs-sonnet",
                    title = "Opus vs Sonnet When to Pick",
                    durationSeconds = 234,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-vs-sonnet.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude Opus and Sonnet by matching model capabilities to your actual workload needs rather than defaults or marketing.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-production",
                    title = "Opus 4.7 in Production",
                    durationSeconds = 275,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to deploy Claude Opus 4.7 in production by understanding its strengths, when to use it, and the engineering patterns that make the difference between a feature that ships and one that doesn't.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-sonnet-4-6",
            title = "Claude Sonnet 4.6",
            description = "Learn how to evaluate and deploy Claude Sonnet 4.6 as a balanced, cost-effective AI model by understanding its strengths, trade-offs, and production best practices.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-overview",
                    title = "Sonnet 4.6 Overview",
                    durationSeconds = 276,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate and deploy Claude Sonnet 4.6 as a balanced, cost-effective AI model by understanding its strengths, trade-offs, and production best practices.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-cost-quality",
                    title = "Cost vs Quality Sweet Spot",
                    durationSeconds = 234,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-cost-quality.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to find the cost-versus-quality sweet spot when choosing Claude Sonnet 4.6 for your AI engineering projects.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-tool-use",
                    title = "Tool Use with Sonnet",
                    durationSeconds = 211,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-tool-use.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Tool use with Claude Sonnet 4.6 is a deliberate engineering decision about matching model capabilities to your workload, not a default choice.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-vision",
                    title = "Sonnet Vision",
                    durationSeconds = 232,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-vision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Sonnet 4.6's vision capabilities as a deliberate engineering choice, not a default.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-vs-others",
                    title = "Sonnet vs Haiku vs Opus",
                    durationSeconds = 240,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-vs-others.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude's Sonnet, Haiku, and Opus models by matching each model's strengths to your specific workload needs rather than defaulting to the most powerful option.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-production",
                    title = "Sonnet 4.6 in Production",
                    durationSeconds = 265,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to strategically choose and deploy Claude Sonnet 4.6 in production by matching model capabilities to workload needs, measuring performance, and avoiding common pitfalls.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-haiku-4-5",
            title = "Claude Haiku 4.5",
            description = "Claude Haiku 4.5 is Anthropic's fast, cheap language model—learn when to use it, how to evaluate it, and how to deploy it confidently in production.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-overview",
                    title = "Haiku 4.5 Overview",
                    durationSeconds = 239,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Haiku 4.5 is Anthropic's fast, cheap language model—learn when to use it, how to evaluate it, and how to deploy it confidently in production.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-latency",
                    title = "Haiku Latency Profile",
                    durationSeconds = 226,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-latency.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate Claude Haiku 4.5's latency profile to make smart model choices for production systems.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-batch",
                    title = "Haiku in Batch Workflows",
                    durationSeconds = 230,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-batch.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use Claude Haiku 4.5 efficiently in batch workflows by understanding its strengths, costs, and when it's the right choice versus other models.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-routing",
                    title = "Routing Cheap Tasks to Haiku",
                    durationSeconds = 248,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-routing.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to route simple, low-cost tasks to Claude Haiku 4.5 to build fast, affordable AI systems that actually ship.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-vs-mini",
                    title = "Haiku vs GPT-4o-mini vs Flash",
                    durationSeconds = 224,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-vs-mini.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude Haiku, GPT-4o-mini, and Flash by matching model capabilities to your workload's cost, latency, and quality needs.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-production",
                    title = "Haiku 4.5 in Production",
                    durationSeconds = 202,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to deploy Claude Haiku 4.5 in production by matching the model to your workload's actual requirements rather than defaults.",
                ),
            ),
        ),
    )
}
