package com.lillytech.aischool.core.model

/**
 * Structured mirror of the AI School catalog, generated from the content
 * pipeline's feed by `pipeline/bundle_into_apps.py`.
 *
 * The network layer prefers the live `syllabus.json` feed; this seed keeps
 * both app flavors fully functional offline (and is the bundled, no-hosting
 * content of record). Do not hand-edit; re-run the bundler to refresh.
 */
object SeedSyllabus {

    val courses: List<Course> = listOf(
        Course(
            id = "anthropic-claude-claude-models-overview",
            title = "Claude Models Overview",
            description = "Learn the Claude model family tiers—Opus, Sonnet, and Haiku—and how to make model-selection, prompt, tool, and production decisions that ship better products faster and cheaper.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-claude-models-overview-claude-family-overview",
                    title = "Claude Family Overview",
                    durationSeconds = 79,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/claude-family-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the Claude model family tiers—Opus, Sonnet, and Haiku—and how to make model-selection, prompt, tool, and production decisions that ship better products faster and cheaper.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-opus-sonnet-haiku-positioning",
                    title = "Opus / Sonnet / Haiku Positioning",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/opus-sonnet-haiku-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Claude's three model tiers—Opus for complex reasoning, Sonnet for balanced production work, and Haiku for speed and cost—and build them into a defensible engineering system.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-family-pricing-shape",
                    title = "Family Pricing Shape",
                    durationSeconds = 90,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/family-pricing-shape.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right Claude model tier and build a defensible decision chain for production AI features.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-context-windows-across-the-family",
                    title = "Context Windows Across the Family",
                    durationSeconds = 88,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/context-windows-across-the-family.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right Claude model tier, design your prompts and tools, engineer your context strategy, and build evaluation loops before shipping production systems.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-family-vs-external-models",
                    title = "Family vs External Models",
                    durationSeconds = 99,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/family-vs-external-models.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the decision chain for building Claude-backed features: pick the right model tier, design prompts with structure, engineer context strategy, and ship with evals and production safeguards.",
                ),
                Lesson(
                    id = "anthropic-claude-claude-models-overview-picking-a-family-tier",
                    title = "Picking a Family Tier",
                    durationSeconds = 95,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/claude-models-overview/picking-a-family-tier.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right Claude model tier—Opus, Sonnet, or Haiku—by matching latency, cost, and quality needs to your production system.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-opus-deep-dive",
            title = "Opus Deep Dive",
            description = "Learn how to build production Claude applications by treating model selection, prompting, tool design, evaluation, and deployment as a deliberate chain of engineering decisions.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-47-overview",
                    title = "Opus 4.7 Overview",
                    durationSeconds = 87,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-47-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to build production Claude applications by treating model selection, prompting, tool design, evaluation, and deployment as a deliberate chain of engineering decisions.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-1m-context-capability",
                    title = "1M Context Capability",
                    durationSeconds = 107,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/1m-context-capability.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Opus's million-token context window by anchoring decisions in user value, choosing the right model tier, designing prompts carefully, engineering context strategy, and building evaluation and production monitoring before shipping.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-frontier-reasoning",
                    title = "Frontier Reasoning",
                    durationSeconds = 107,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/frontier-reasoning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the foundational pattern for building Claude-backed systems in production: anchor your work in user value, pick the right model tier, design prompts deliberately, wire tools carefully, engineer your context strategy, build evaluations before shipping, and deploy with operational safeguards.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-cost-latency-profile",
                    title = "Cost & Latency Profile",
                    durationSeconds = 92,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/cost-latency-profile.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the decision chain for building production Claude features: pick the right model tier, design intentional prompts, engineer context strategy, and ship with evals and operational monitoring.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-vs-sonnet-decision",
                    title = "Opus vs Sonnet Decision",
                    durationSeconds = 97,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-vs-sonnet-decision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when to pick Claude Opus versus Sonnet by matching model tier to your latency, cost, and quality needs, then operationalize that choice through prompt design, tool wiring, evaluation, and production scaffolding.",
                ),
                Lesson(
                    id = "anthropic-claude-opus-deep-dive-opus-workload-patterns",
                    title = "Opus Workload Patterns",
                    durationSeconds = 91,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/opus-deep-dive/opus-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the seven-step pattern for building production Claude applications: anchor to user value, pick the right model tier, design prompts carefully, wire tools with error handling, engineer your context strategy, build evals before shipping, and deploy with operational safeguards.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-sonnet-deep-dive",
            title = "Sonnet Deep Dive",
            description = "Claude Sonnet 4.6 is the production workhorse model that balances cost, quality, and speed—master the decision chain around model selection, prompt design, tool wiring, evaluation, and operational scaffolding to ship Claude-backed features that scale.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-sonnet-46-overview",
                    title = "Sonnet 4.6 Overview",
                    durationSeconds = 78,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/sonnet-46-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Sonnet 4.6 is the production workhorse model that balances cost, quality, and speed—master the decision chain around model selection, prompt design, tool wiring, evaluation, and operational scaffolding to ship Claude-backed features that scale.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-production-workhorse-positioning",
                    title = "Production Workhorse Positioning",
                    durationSeconds = 89,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/production-workhorse-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to position Claude Sonnet as a production workhorse by anchoring decisions in user value, picking the right model tier, designing prompts carefully, wiring tools with safety, managing context strategy, building evaluation sets before shipping, and deploying with operational safeguards.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-price-quality-latency-trade-off",
                    title = "Price / Quality / Latency Trade-off",
                    durationSeconds = 88,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/price-quality-latency-trade-off.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the mental model and operational checklist for making defensible model-selection, prompt-design, and production-deployment decisions when building Claude-backed features at scale.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-sonnet-workload-patterns",
                    title = "Sonnet Workload Patterns",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/sonnet-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Sonnet as a production workhorse by anchoring decisions in user outcomes, picking the right model tier, and building evaluation loops before shipping.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-migrating-from-earlier-sonnet",
                    title = "Migrating from Earlier Sonnet",
                    durationSeconds = 90,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/migrating-from-earlier-sonnet.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the decision chain for building production Claude applications: model selection, prompt design, tool wiring, context strategy, evaluation, and operational deployment.",
                ),
                Lesson(
                    id = "anthropic-claude-sonnet-deep-dive-opus-sonnet-cascade",
                    title = "Opus-Sonnet Cascade",
                    durationSeconds = 98,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/sonnet-deep-dive/opus-sonnet-cascade.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the Opus-Sonnet cascade pattern to build production Claude systems that balance cost, latency, and quality through deliberate model selection, prompt engineering, tool design, and evaluation before shipping.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-haiku-deep-dive",
            title = "Haiku Deep Dive",
            description = "Master Claude Haiku 4.5 by treating AI engineering as a chain of deliberate decisions: model tier, prompt design, tool wiring, context strategy, evaluation, and production operations.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-45-overview",
                    title = "Haiku 4.5 Overview",
                    durationSeconds = 92,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-45-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku 4.5 by treating AI engineering as a chain of deliberate decisions: model tier, prompt design, tool wiring, context strategy, evaluation, and production operations.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-fast-cheap-positioning",
                    title = "Fast & Cheap Positioning",
                    durationSeconds = 97,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/fast-cheap-positioning.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku for fast, cheap production work by anchoring decisions in user metrics, picking the right model tier, designing prompts carefully, and shipping with evals and operational safeguards.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-workload-patterns",
                    title = "Haiku Workload Patterns",
                    durationSeconds = 94,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-workload-patterns.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master Claude Haiku by treating every AI feature as a chain of engineering decisions: model tier, prompt design, tools, context strategy, evaluation, and production operations.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-latency-targets",
                    title = "Latency Targets",
                    durationSeconds = 95,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/latency-targets.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master latency targets for Claude Haiku by anchoring your work in user metrics, picking the right model tier, and building evaluation loops before shipping to production.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-cost-optimisation",
                    title = "Cost Optimisation",
                    durationSeconds = 91,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/cost-optimisation.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to build cost-effective Claude integrations by treating it as a chain of deliberate decisions—from model selection through production operations—and always eval before shipping.",
                ),
                Lesson(
                    id = "anthropic-claude-haiku-deep-dive-haiku-first-design-pattern",
                    title = "Haiku-First Design Pattern",
                    durationSeconds = 112,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/haiku-deep-dive/haiku-first-design-pattern.html",
                    isAutomotiveSafe = true,
                    audioSummary = "The haiku-first design pattern teaches you to build Claude-backed features by anchoring in user metrics, choosing the right model tier for cost and latency, designing prompts with structure, wiring tools with clear error handling, engineering your context strategy, building evaluation sets before shipping, and deploying with operational safeguards.",
                ),
            ),
        ),
        Course(
            id = "anthropic-claude-model-selection",
            title = "Model Selection",
            description = "Master the decision framework for picking the right Claude model tier and operationalizing it through prompt design, tool wiring, evaluation, and production deployment.",
            category = "Anthropic Claude",
            lessons = listOf(
                Lesson(
                    id = "anthropic-claude-model-selection-model-selection-overview",
                    title = "Model Selection Overview",
                    durationSeconds = 99,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/model-selection-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Master the decision framework for picking the right Claude model tier and operationalizing it through prompt design, tool wiring, evaluation, and production deployment.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-decision-framework",
                    title = "Decision Framework",
                    durationSeconds = 94,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/decision-framework.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the decision framework for choosing Claude models and building production-grade AI features: anchor work in user metrics, pick the right model tier for your latency and cost needs, design prompts carefully, wire tools with clear schemas, engineer context strategy, build evaluation sets before shipping, and deploy with operational safeguards.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-benchmark-mapping",
                    title = "Benchmark Mapping",
                    durationSeconds = 101,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/benchmark-mapping.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the decision framework and practical patterns for selecting the right Claude model for your use case and building production systems that scale.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-cascade-pattern",
                    title = "Cascade Pattern",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/cascade-pattern.html",
                    isAutomotiveSafe = true,
                    audioSummary = "The cascade pattern is a decision framework for selecting the right Claude model and building production systems by reasoning through latency, cost, quality, prompts, tools, context strategy, and evaluation before shipping.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-eval-discipline",
                    title = "Eval Discipline",
                    durationSeconds = 97,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/eval-discipline.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn the seven-step eval discipline framework that defensible Claude-backed teams use to make repeatable model, prompt, tool, and production decisions.",
                ),
                Lesson(
                    id = "anthropic-claude-model-selection-selection-template",
                    title = "Selection Template",
                    durationSeconds = 95,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/anthropic-claude/model-selection/selection-template.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn a decision-driven framework for choosing and deploying Claude models in production by anchoring in user value, matching model tiers to budgets, and building evaluation loops before shipping.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-claude-code",
            title = "Claude Code",
            description = "Claude Code is a terminal-native AI coding assistant with slash commands, hooks, and configuration options that transform your development workflow when set up intentionally.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-claude-code-claude-code-overview",
                    title = "Claude Code Overview",
                    durationSeconds = 82,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Code is a terminal-native AI coding assistant with slash commands, hooks, and configuration options that transform your development workflow when set up intentionally.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-slash-commands",
                    title = "Slash Commands and Skills",
                    durationSeconds = 74,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-slash-commands.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn slash commands and skills in Claude Code CLI to work faster by leaning into the tool's strengths instead of fighting its design.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-hooks",
                    title = "Hooks and Automation",
                    durationSeconds = 81,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-hooks.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Hooks and automation let you create intelligent workflows in Claude Code that run tasks automatically after specific coding actions, turning you from a casual user into a power user.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-subagents",
                    title = "Sub-Agents and Parallelism",
                    durationSeconds = 75,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-subagents.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Sub-agents and parallelism in Claude Code let you run multiple AI tasks at once, but the real power is knowing when to use them deliberately instead of defaulting to complexity.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-mcp",
                    title = "MCP Servers",
                    durationSeconds = 77,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-mcp.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how MCP servers extend Claude Code as a power-user feature to integrate custom data sources and tools into your terminal AI coding workflow.",
                ),
                Lesson(
                    id = "ai-tools-claude-code-claude-code-team-workflows",
                    title = "Team Workflows and Settings",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/claude-code/claude-code-team-workflows.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to configure Claude Code as a team tool by mastering workflows, settings, and the mental models that separate casual users from power users.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-cursor-editor",
            title = "Cursor Editor",
            description = "Cursor is an AI-first code editor that multiplies your coding speed when you align your workflow with its strengths rather than fighting its design.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-overview",
                    title = "Cursor Overview",
                    durationSeconds = 77,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Cursor is an AI-first code editor that multiplies your coding speed when you align your workflow with its strengths rather than fighting its design.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-tab",
                    title = "Cursor Tab Autocomplete",
                    durationSeconds = 90,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-tab.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Cursor Tab Autocomplete is a deliberate workflow choice that separates casual users from power users—master it by understanding its strengths, integrating it with your stack, and measuring real time savings.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-composer-agent",
                    title = "Composer and Agent Mode",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-composer-agent.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Composer and Agent Mode are deliberate workflow choices in Cursor that separate casual users from power users—understand when and how to use them, not just memorize the menu items.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-rules",
                    title = "cursorrules and Project Rules",
                    durationSeconds = 74,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-rules.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use .cursorrules and project rules in Cursor to encode your team's coding standards and unlock power-user productivity gains.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-mcp",
                    title = "Cursor MCP Integration",
                    durationSeconds = 82,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-mcp.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Cursor MCP integration is about deliberately configuring Cursor as your AI coding partner by mastering its core features—Tab autocomplete, Composer mode, project rules, and server connections—rather than using it casually off-the-shelf.",
                ),
                Lesson(
                    id = "ai-tools-cursor-editor-cursor-team",
                    title = "Cursor for Teams",
                    durationSeconds = 81,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/cursor-editor/cursor-team.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Cursor for Teams is a workflow choice that multiplies your shipping speed when you match the tool's strengths to your actual needs and build deliberate habits around it.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-github-copilot-tool",
            title = "GitHub Copilot Tool",
            description = "GitHub Copilot Overview teaches you how to use AI coding assistance deliberately as a workflow tool, not just follow defaults.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-overview",
                    title = "Copilot Overview",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GitHub Copilot Overview teaches you how to use AI coding assistance deliberately as a workflow tool, not just follow defaults.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-inline-chat",
                    title = "Inline Suggestions and Chat",
                    durationSeconds = 71,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-inline-chat.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use GitHub Copilot's inline suggestions and chat as a deliberate workflow choice, not a default feature.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-workspace",
                    title = "Copilot Workspace",
                    durationSeconds = 81,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-workspace.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Copilot Workspace is a deliberate workflow choice that separates casual users from power users by applying intentional patterns and configurations rather than default behaviors.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-agent-mode",
                    title = "Copilot Agent Mode",
                    durationSeconds = 88,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-agent-mode.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Copilot Agent Mode is a deliberate workflow choice that lets you leverage GitHub Copilot's full power by understanding its strengths and building habits around them.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-instructions",
                    title = "Custom Instructions",
                    durationSeconds = 82,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-instructions.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Custom instructions in GitHub Copilot let you guide the AI's behavior toward your workflow, turning casual users into power users through deliberate configuration choices.",
                ),
                Lesson(
                    id = "ai-tools-github-copilot-tool-copilot-enterprise",
                    title = "Copilot Enterprise",
                    durationSeconds = 83,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/github-copilot-tool/copilot-enterprise.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Copilot Enterprise is a powerful AI coding assistant that requires deliberate workflow design and configuration to unlock significant productivity gains for development teams.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-aider",
            title = "Aider",
            description = "Aider is a terminal-based AI pair programmer that helps you code faster by understanding your repo and working with Git, but only if you use it deliberately for the right job.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-aider-aider-overview",
                    title = "Aider Overview",
                    durationSeconds = 73,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Aider is a terminal-based AI pair programmer that helps you code faster by understanding your repo and working with Git, but only if you use it deliberately for the right job.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-architect-edit",
                    title = "Architect and Edit Modes",
                    durationSeconds = 63,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-architect-edit.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Aider's architect and edit modes to code faster with an AI pair programmer.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-repo-map",
                    title = "Repo Map",
                    durationSeconds = 78,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-repo-map.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Repo map is a workflow choice in Aider that separates casual users from power users—understand the underlying patterns and when to use the tool, not just memorizing commands.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-git",
                    title = "Git-Aware Editing",
                    durationSeconds = 74,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-git.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Git-aware editing in Aider is a deliberate workflow choice that separates casual users from power users through intentional patterns and configuration.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-voice",
                    title = "Aider Voice Coding",
                    durationSeconds = 75,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-voice.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to use Aider's voice coding feature effectively as a deliberate workflow choice, not a casual add-on, by understanding when it fits your needs and how power users leverage it.",
                ),
                Lesson(
                    id = "ai-tools-aider-aider-models",
                    title = "Choosing Models for Aider",
                    durationSeconds = 74,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/aider/aider-models.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Choosing the right model for Aider means treating it as a deliberate workflow decision based on your needs, not accepting defaults.",
                ),
            ),
        ),
        Course(
            id = "ai-tools-continue-dev",
            title = "Continue Dev",
            description = "Continue is an open-source AI coding assistant for VS Code and JetBrains that compounds your workflow speed through intentional configuration and deliberate habit patterns, not casual defaults.",
            category = "AI Tools",
            lessons = listOf(
                Lesson(
                    id = "ai-tools-continue-dev-continue-overview",
                    title = "Continue Overview",
                    durationSeconds = 81,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Continue is an open-source AI coding assistant for VS Code and JetBrains that compounds your workflow speed through intentional configuration and deliberate habit patterns, not casual defaults.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-config",
                    title = "config.json Configuration",
                    durationSeconds = 76,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-config.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to configure Continue's config.json file to customize your AI coding assistant with models, context providers, and slash commands for faster development workflows.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-context-providers",
                    title = "Context Providers",
                    durationSeconds = 89,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-context-providers.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Context providers in Continue are deliberate workflow choices that separate casual users from power users by controlling what information the AI assistant has access to when helping you code.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-custom-commands",
                    title = "Custom Slash Commands",
                    durationSeconds = 83,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-custom-commands.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn to create custom slash commands in Continue to build reusable AI coding workflows tailored to your development process.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-self-hosted",
                    title = "Self-Hosted Continue",
                    durationSeconds = 96,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-self-hosted.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to configure and self-host the Continue AI coding assistant to match your workflow, with the right models, context providers, and custom commands.",
                ),
                Lesson(
                    id = "ai-tools-continue-dev-continue-vs-cursor",
                    title = "Continue vs Cursor",
                    durationSeconds = 93,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-tools/continue-dev/continue-vs-cursor.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose between Continue and Cursor as AI coding assistants and when each tool fits your workflow best.",
                ),
            ),
        ),
        Course(
            id = "ai-models-gpt-5",
            title = "GPT-5",
            description = "GPT-5 is OpenAI's flagship model; master its capabilities, pricing, and context window to make confident deployment decisions in production systems.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-overview",
                    title = "GPT-5 Overview",
                    durationSeconds = 95,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GPT-5 is OpenAI's flagship model; master its capabilities, pricing, and context window to make confident deployment decisions in production systems.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-capabilities",
                    title = "GPT-5 Capabilities and Benchmarks",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-capabilities.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to evaluate GPT-5's actual capabilities and benchmarks to make smart model selection decisions for your AI projects.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-context-multimodal",
                    title = "Context Window and Multimodal",
                    durationSeconds = 73,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-context-multimodal.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to match GPT-5's context window and multimodal capabilities to your workload, and why this engineering decision matters more than following hype.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-tool-use",
                    title = "Native Tool Use",
                    durationSeconds = 85,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-tool-use.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Native tool use in GPT-5 is a deliberate engineering choice to match your workload, not a default—pick the model that fits your problem, measure quality and cost on your actual data, and only upgrade when cheaper alternatives fall short.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-pricing",
                    title = "Pricing and Cost Optimization",
                    durationSeconds = 111,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-pricing.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose the right AI model by understanding pricing, capabilities, and cost tradeoffs rather than defaulting to the most expensive or popular option.",
                ),
                Lesson(
                    id = "ai-models-gpt-5-gpt-5-production",
                    title = "GPT-5 in Production",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-5/gpt-5-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and deploy GPT-5 in production by matching its capabilities, cost, and constraints to your actual workload rather than defaulting to it.",
                ),
            ),
        ),
        Course(
            id = "ai-models-gpt-4o",
            title = "GPT-4o",
            description = "GPT-4o is OpenAI's versatile multimodal model that handles text, vision, and audio—choose it thoughtfully based on your actual workload needs, not hype.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-overview",
                    title = "GPT-4o Overview",
                    durationSeconds = 80,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GPT-4o is OpenAI's versatile multimodal model that handles text, vision, and audio—choose it thoughtfully based on your actual workload needs, not hype.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-vision",
                    title = "GPT-4o Vision",
                    durationSeconds = 83,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-vision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "GPT-4o Vision is OpenAI's multimodal model that processes images alongside text; use it only when your workload actually needs it, after benchmarking against cheaper alternatives.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-audio",
                    title = "GPT-4o Audio",
                    durationSeconds = 80,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-audio.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use GPT-4o Audio Realtime by treating model selection as a deliberate engineering decision based on your actual workload, not marketing hype.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-mini",
                    title = "GPT-4o-mini for Cost",
                    durationSeconds = 79,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-mini.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose gpt-4o-mini strategically based on your actual workload needs rather than defaults, balancing cost, quality, and latency.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-structured-outputs",
                    title = "Structured Outputs",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-structured-outputs.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Structured outputs in GPT-4o let you get reliable, formatted responses from the model, and choosing when to use them is a deliberate engineering decision, not a default.",
                ),
                Lesson(
                    id = "ai-models-gpt-4o-gpt-4o-production",
                    title = "GPT-4o in Production",
                    durationSeconds = 82,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/gpt-4o/gpt-4o-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and deploy GPT-4o in production by matching model capabilities to your workload rather than fitting your problem to the model.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-opus-4-7",
            title = "Claude Opus 4.7",
            description = "Claude Opus 4.7 is Anthropic's flagship model for complex reasoning and coding—understand its strengths, costs, and capabilities to make smart model choices in production.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-overview",
                    title = "Claude Opus 4.7 Overview",
                    durationSeconds = 91,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Opus 4.7 is Anthropic's flagship model for complex reasoning and coding—understand its strengths, costs, and capabilities to make smart model choices in production.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-1m-context",
                    title = "1M Token Context Window",
                    durationSeconds = 83,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-1m-context.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Opus 4.7's 1M token context window lets you fit massive amounts of information into a single request, but you should only use it when your actual workload needs it, not just because it exists.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-coding",
                    title = "Opus 4.7 for Coding",
                    durationSeconds = 87,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-coding.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Opus 4.7 for coding tasks, including its 1M context window and prompt caching capabilities.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-agents",
                    title = "Opus 4.7 for Agents",
                    durationSeconds = 96,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-agents.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Opus 4.7 for agent applications, and master the engineering decision-making that separates production systems from projects that don't ship.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-vs-sonnet",
                    title = "Opus vs Sonnet When to Pick",
                    durationSeconds = 66,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-vs-sonnet.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when to choose Claude Opus versus Sonnet by matching model capabilities to your workload's actual needs, not marketing benchmarks.",
                ),
                Lesson(
                    id = "ai-models-claude-opus-4-7-opus-4-7-production",
                    title = "Opus 4.7 in Production",
                    durationSeconds = 89,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-opus-4-7/opus-4-7-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and deploy Claude Opus 4.7 in production by matching the model's strengths to your workload, not the other way around.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-sonnet-4-6",
            title = "Claude Sonnet 4.6",
            description = "Claude Sonnet 4.6 is Anthropic's balanced workhorse model—learn when and why to choose it based on cost, quality, and your actual workload needs rather than hype.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-overview",
                    title = "Sonnet 4.6 Overview",
                    durationSeconds = 89,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Sonnet 4.6 is Anthropic's balanced workhorse model—learn when and why to choose it based on cost, quality, and your actual workload needs rather than hype.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-cost-quality",
                    title = "Cost vs Quality Sweet Spot",
                    durationSeconds = 82,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-cost-quality.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to match Claude Sonnet 4.6 to your workload by balancing cost and quality rather than picking a model by hype.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-tool-use",
                    title = "Tool Use with Sonnet",
                    durationSeconds = 87,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-tool-use.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to strategically use Claude Sonnet 4.6's tool-use capabilities as an engineering decision, not a default, by understanding when it fits your workload and how to evaluate it properly.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-vision",
                    title = "Sonnet Vision",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-vision.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Sonnet 4.6 Vision is Anthropic's balanced AI model that pairs cost-effectiveness with quality, and choosing it requires understanding your workload's actual needs rather than defaulting to it.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-vs-others",
                    title = "Sonnet vs Haiku vs Opus",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-vs-others.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to pick the right Claude model—Sonnet, Haiku, or Opus—by matching your workload to each model's strengths, cost, and capabilities rather than defaulting to the obvious choice.",
                ),
                Lesson(
                    id = "ai-models-claude-sonnet-4-6-sonnet-4-6-production",
                    title = "Sonnet 4.6 in Production",
                    durationSeconds = 77,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-sonnet-4-6/sonnet-4-6-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to choose and deploy Claude Sonnet 4.6 in production by matching the model to your workload, building evals, and monitoring costs and latency.",
                ),
            ),
        ),
        Course(
            id = "ai-models-claude-haiku-4-5",
            title = "Claude Haiku 4.5",
            description = "Learn when and how to use Claude Haiku 4.5, Anthropic's fast and affordable model, by understanding its strengths, costs, and real-world deployment patterns.",
            category = "AI Models",
            lessons = listOf(
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-overview",
                    title = "Haiku 4.5 Overview",
                    durationSeconds = 86,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-overview.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Haiku 4.5, Anthropic's fast and affordable model, by understanding its strengths, costs, and real-world deployment patterns.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-latency",
                    title = "Haiku Latency Profile",
                    durationSeconds = 94,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-latency.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Claude Haiku 4.5 is a fast, cheap model designed for high-volume tasks—learn when to use it, why latency and cost matter, and how to evaluate it against alternatives in production.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-batch",
                    title = "Haiku in Batch Workflows",
                    durationSeconds = 95,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-batch.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to use Claude Haiku 4.5 in batch workflows to process high-volume tasks cheaply and efficiently.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-routing",
                    title = "Routing Cheap Tasks to Haiku",
                    durationSeconds = 74,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-routing.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to route simple tasks to Claude Haiku 4.5, Anthropic's fast and cheap model, by matching workload characteristics to model strengths rather than defaulting to expensive alternatives.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-vs-mini",
                    title = "Haiku vs GPT-4o-mini vs Flash",
                    durationSeconds = 84,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-vs-mini.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn when and how to choose between Claude Haiku, GPT-4o-mini, and Flash models based on your actual workload needs rather than marketing hype.",
                ),
                Lesson(
                    id = "ai-models-claude-haiku-4-5-haiku-4-5-production",
                    title = "Haiku 4.5 in Production",
                    durationSeconds = 80,
                    audioUrl = "",
                    visualContentUrl = "https://www.lillytechsystems.com/ai-models/claude-haiku-4-5/haiku-4-5-production.html",
                    isAutomotiveSafe = true,
                    audioSummary = "Learn how to deploy Claude Haiku 4.5 in production by matching the model's strengths to your workload, measuring quality and cost, and avoiding the common pitfall of choosing models based on hype rather than actual requirements.",
                ),
            ),
        ),
    )
}
